name: Deploy Static Site

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Git LFS
      run: |
        sudo apt-get update
        sudo apt-get install -y git-lfs
        git lfs install
        
    - name: Download website with wget
      run: |
        wget --mirror \
             --convert-links \
             --adjust-extension \
             --page-requisites \
             --no-parent \
             --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
             --no-check-certificate \
             -e robots=off \
             https://bayareatamilmanram.org/
             
    - name: Prepare the deployment
      run: |
        # Move the downloaded site to a temporary directory
        mv bayareatamilmanram.org/ /tmp/downloaded-site/
        
        # Checkout again to ensure we have all files
        git checkout main
        
        # Remove everything except .git and .github directories
        find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '.github' -exec rm -rf {} +
        
        # Move the downloaded content back
        mv /tmp/downloaded-site/* .
        rmdir /tmp/downloaded-site
        
        # Initialize Git LFS in case it's not set up
        git lfs track "*.jpg" "*.png" "*.mp4" "*.zip" "*.jpeg" || true
        
        # Ensure .gitignore exists
        echo -e "wp-content/cache/\n*.tmp\n*.bak\nnode_modules/\nvendor/" > .gitignore
        
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Automated update of WordPress site with Git LFS"
        git push origin main
